# Generated by Django 5.0.6 on 2024-07-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ref_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=20, null=True)),
                ('ref_no', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
