# Generated by Django 5.0.6 on 2024-07-25 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_invoice', '0003_masterfile_category_sales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category_sales',
            options={'verbose_name_plural': 'Category_Sales'},
        ),
        migrations.AlterModelOptions(
            name='invoicesummary',
            options={'verbose_name_plural': 'InvoiceSummary'},
        ),
        migrations.AlterModelOptions(
            name='masterfile',
            options={'verbose_name_plural': 'MasterFile'},
        ),
        migrations.AddField(
            model_name='masterfile',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_invoice.category_sales'),
        ),
        migrations.AddField(
            model_name='masterfile',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
