# Generated by Django 5.0.6 on 2024-07-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_invoice', '0004_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='itemnumber',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
