# Generated by Django 5.0.6 on 2024-07-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_invoice', '0006_alter_master_itemnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='myimage',
            field=models.ImageField(blank=True, null=True, upload_to='master_images/'),
        ),
    ]
