# Generated by Django 5.0.6 on 2024-07-31 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_invoice', '0007_master_myimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales_entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemnumber', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('description', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_invoice.master')),
            ],
        ),
    ]
