# Generated by Django 5.0.6 on 2024-07-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_invoice', '0010_sales_entry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_entry',
            name='quantity',
            field=models.IntegerField(blank=True, max_length=7, null=True),
        ),
    ]
