# Generated by Django 5.0.6 on 2024-08-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_invoice', '0012_alter_sales_entry_itemnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_entry',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
