# Generated by Django 5.0.6 on 2024-08-06 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_invoice', '0014_tax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tax',
            options={'verbose_name_plural': 'Tax'},
        ),
    ]
