# Generated by Django 5.0.6 on 2024-07-07 00:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_import', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phil_city',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
