# Generated by Django 5.0.6 on 2024-07-18 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='image-default/default-image.png', upload_to='user-profile/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ImageField(default='image-default/default-image.png', upload_to='cover-photo/'),
        ),
    ]
