# Generated by Django 5.0.6 on 2024-07-18 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0002_alter_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccess',
            name='new_user',
            field=models.BooleanField(default=True),
        ),
    ]
