# Generated by Django 5.0.6 on 2024-08-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0003_useraccess_new_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccess',
            name='post_notary_access',
            field=models.BooleanField(default=False),
        ),
    ]
