# Generated by Django 5.0.6 on 2024-07-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_notary', '0002_notarized_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='notarized_documents',
            name='myfile',
            field=models.FileField(null=True, upload_to='myfiles/'),
        ),
    ]
