# Generated by Django 5.0.6 on 2024-07-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_notary', '0003_notarized_documents_myfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='notarized_documents',
            name='myimage',
            field=models.ImageField(null=True, upload_to='myimages/'),
        ),
    ]
