# Generated by Django 5.0.6 on 2024-07-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_notary', '0004_notarized_documents_myimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='notarized_documents',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notarized_documents',
            name='bookno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notarized_documents',
            name='pageno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notarized_documents',
            name='recordno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notarized_documents',
            name='myfile',
            field=models.FileField(blank=True, null=True, upload_to='myfiles/'),
        ),
        migrations.AlterField(
            model_name='notarized_documents',
            name='myimage',
            field=models.ImageField(blank=True, null=True, upload_to='myimages/'),
        ),
    ]
