# Generated by Django 5.0.6 on 2024-07-04 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_notary', '0006_alter_notarized_documents_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notarized_documents',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_notary.notary_category'),
        ),
    ]
