# Generated by Django 5.0.6 on 2024-07-06 02:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_notary', '0008_alter_notary_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notarized_documents',
            name='bookno',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='notarized_documents',
            name='pageno',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='notarized_documents',
            name='recordno',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
