# Generated by Django 5.0.6 on 2024-07-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_notary', '0009_alter_notarized_documents_bookno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notarized_documents',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
