# Generated by Django 5.0.6 on 2024-08-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_notary', '0009_alter_notarized_documents_bookno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notarized_documents',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='notarized_documents',
            name='tax_data',
            field=models.JSONField(blank=True, help_text="Data format:{'tax_type':{'tax_percentage':'tax_amount'}}", null=True),
        ),
        migrations.AddField(
            model_name='notarized_documents',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='notarized_documents',
            name='total_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notarized_documents',
            name='total_tax',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
