# Generated by Django 5.0.6 on 2024-08-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_notary', '0011_notarized_documents_total_tax_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notarized_documents',
            name='total_data',
            field=models.JSONField(blank=True, help_text="Data format : {'tax_type'}:{'tax_percentage': {tax_amount}}", null=True),
        ),
    ]
