# Generated by Django 5.0.6 on 2024-08-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_notary', '0012_alter_notarized_documents_total_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='notarized_documents',
            name='unique_key',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
