# Generated by Django 5.0.6 on 2024-08-12 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_notary', '0013_notarized_documents_unique_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notarized_documents',
            name='total_tax',
        ),
    ]
