# Generated by Django 5.0.6 on 2024-08-13 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_notary', '0014_remove_notarized_documents_total_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='notarized_documents',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
    ]
