# Generated by Django 5.0.6 on 2024-08-13 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_notary', '0018_alter_notarized_documents_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notarized_documents',
            old_name='unique_key',
            new_name='posted_serial',
        ),
    ]
