# Generated by Django 5.0.6 on 2024-08-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_notary', '0020_notary_posting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notarized_documents',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
