# Generated by Django 5.0.6 on 2024-08-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_notary', '0021_alter_notarized_documents_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notary_posting',
            name='posted_serial',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
