# Generated by Django 5.0.6 on 2024-08-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_notary', '0022_alter_notary_posting_posted_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notary_posting',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='notary_posting',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
