# Generated by Django 5.0.6 on 2024-08-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_notary', '0023_notary_posting_tax_notary_posting_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='notarized_documents',
            name='or_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
