# Generated by Django 5.0.6 on 2024-10-15 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_notary', '0024_notarized_documents_or_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notarized_documents',
            options={'verbose_name_plural': 'Notarized Documents'},
        ),
        migrations.AlterModelOptions(
            name='notary_category',
            options={'verbose_name_plural': 'Notary Categories'},
        ),
    ]
