# Generated by Django 5.0.6 on 2024-09-19 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr', models.DateTimeField(max_length=3, null=True)),
                ('curr_desc', models.DateTimeField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='chart_acct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chrt_accno', models.CharField(blank=True, max_length=10, null=True)),
                ('chrt_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('chrt_H_D', models.CharField(blank=True, max_length=1, null=True)),
                ('chrt_curr', models.CharField(blank=True, max_length=1, null=True)),
                ('beg_bal', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=13, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('chrt_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
