# Generated by Django 5.0.6 on 2024-09-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounting', '0002_alter_currency_curr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='curr_desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
