# Generated by Django 5.0.6 on 2024-09-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounting', '0003_alter_currency_curr_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart_acct',
            name='chrt_curr',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
