# Generated by Django 5.0.6 on 2024-09-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounting', '0004_alter_chart_acct_chrt_curr'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart_acct',
            name='date_last_movement',
            field=models.DateTimeField(null=True),
        ),
    ]
