# Generated by Django 5.0.6 on 2024-09-19 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounting', '0005_chart_acct_date_last_movement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ytdfd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucherno', models.IntegerField(default=0)),
                ('voucher_date', models.DateField(blank=True, null=True)),
                ('dr', models.CharField(blank=True, max_length=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=13)),
                ('project', models.CharField(blank=True, max_length=10, null=True)),
                ('accno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_accounting.chart_acct')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
