# Generated by Django 5.0.6 on 2024-11-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrec',
            name='mobile',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
