# Generated by Django 5.0.6 on 2024-11-20 01:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sample', '0002_studentrec_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrec',
            name='firstname',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9 ]+$', 'only AlphaNumeric are allowed')]),
        ),
        migrations.AlterField(
            model_name='studentrec',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\- ]*$', 'Alpha only ^^^')]),
        ),
        migrations.AlterField(
            model_name='studentrec',
            name='mobile',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator('\\d\\d\\d-\\d\\d\\d-\\d\\d\\d\\d', 'only AlphaNumeric are allowed')], verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='studentrec',
            name='studno',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'only numbers are allowed')]),
        ),
    ]
