# Generated by Django 5.0.6 on 2024-11-20 02:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sample', '0003_alter_studentrec_firstname_alter_studentrec_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrec',
            name='notes',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.RegexValidator('09\\d\\d-\\d\\d\\d-\\d\\d\\d\\d$', message='follow pattern 09xx-xxx-xxxx')]),
        ),
        migrations.AlterField(
            model_name='studentrec',
            name='firstname',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9 ]+$', message='only AlphaNumeric are allowed')]),
        ),
        migrations.AlterField(
            model_name='studentrec',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\- ]*$', message='Alpha only ^^^')]),
        ),
        migrations.AlterField(
            model_name='studentrec',
            name='mobile',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator('09\\d\\d-\\d\\d\\d-\\d\\d\\d\\d$', message='follow pattern 09xx-xxx-xxxx')], verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='studentrec',
            name='studno',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]+$', message='only numbers are allowed')]),
        ),
    ]
